# Prometheus Alert Rules for NetGuard Security

groups:
  - name: security_alerts
    interval: 30s
    rules:
      # High threat detection rate
      - alert: HighThreatDetectionRate
        expr: rate(threats_detected_total[5m]) > 10
        for: 2m
        labels:
          severity: critical
          component: ids
        annotations:
          summary: "High threat detection rate"
          description: "Detecting {{ $value }} threats per second (threshold: 10/s)"

      # DDoS attack detected
      - alert: DDoSAttackDetected
        expr: ddos_attacks_total > 0
        for: 1m
        labels:
          severity: critical
          component: ids
        annotations:
          summary: "DDoS attack detected"
          description: "{{ $value }} DDoS attacks detected in the last minute"

      # Port scan detected
      - alert: PortScanDetected
        expr: port_scans_total > 5
        for: 5m
        labels:
          severity: high
          component: ids
        annotations:
          summary: "Multiple port scans detected"
          description: "{{ $value }} port scans detected in the last 5 minutes"

      # Brute force attack
      - alert: BruteForceAttack
        expr: brute_force_attempts_total > 10
        for: 5m
        labels:
          severity: critical
          component: ids
        annotations:
          summary: "Brute force attack detected"
          description: "{{ $value }} brute force attempts in the last 5 minutes"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} (threshold: 5%)"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          component: infrastructure
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Database connection pool exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: db_connections_active / db_connections_max > 0.9
        for: 2m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of database connections in use"

      # Slow response time
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "Slow API response time"
          description: "95th percentile response time is {{ $value }}s (threshold: 1s)"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanizePercentage }} disk space remaining"

      # Anomaly detection triggered
      - alert: AnomalyDetected
        expr: anomalies_detected_total > 0
        for: 2m
        labels:
          severity: warning
          component: ids
        annotations:
          summary: "Network anomaly detected"
          description: "{{ $value }} anomalies detected in the last 2 minutes"
